### ISSUE TITLE
Avoid escaping punctuation

### ISSUE THREAD

**Issue by mgeier** [classeur/markdown-it-mathjax#2]
First of all, thanks for this great plugin!

If I'm not mistaken, the plugin runs after escaping punctuation, which breaks valid LaTeX math commands like `\,`, `\;`, ...
Would it be possible to run the plugin before the escaping happens, or would this have some unwanted consequences?

**Comment by benweet** [comment]
I think it runs before:

https://github.com/classeur/markdown-it-mathjax/blob/master/markdown-it-mathjax.js#L100

Did you encounter any problem?

**Comment by mgeier** [comment]
Oh, I'm sorry, my mistake!

I forgot to escape the backslash in the input string, so it was removed by the JavaScript parser, not by `markdown-it-mathjax`.

```js
> '\!'
'!'
```

To my defense: I'm new to JavaScript (an I hate it!). In Python it's not necessary to escape the backslash:

```python
>>> '\!'
'\\!'
```

I'm closing this ... sorry for the noise ... and keep up the good work!
